version: 0.0.{build}
skip_tags: true
build:
  project: nslookup2csv.sln
  verbosity: minimal
image: Visual Studio 2015
configuration: Debug
before_build:
  nuget restore nslookup2csv.sln
after_test: 
    - packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\MSTest.exe" -targetargs:"/noresults /noisolation /testcontainer:""UnitTest.dll" -targetdir:".\UnitTest\bin\Debug" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All -output:.\MyProject_coverage.xml -filter:"+[nslookup2csv*]* -[UnitTest*]*""
    - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
    - pip install codecov
    - codecov -f "MyProject_coverage.xml"	
